/** A list of menu ids associated with the main menu in GitHub Desktop */
export type MenuIDs =
  | 'rename-branch'
  | 'delete-branch'
  | 'discard-all-changes'
  | 'stash-all-changes'
  | 'preferences'
  | 'update-branch'
  | 'commit-changes'
  | 'merge-branch'
  | 'rebase-branch'
  | 'view-repository-on-github'
  | 'open-in-shell'
  | 'push'
  | 'pull'
  | 'branch'
  | 'repository'
  | 'go-to-commit-message'
  | 'create-branch'
  | 'show-changes'
  | 'show-stashes'
  | 'show-history'
  | 'show-repository-list'
  | 'show-branches-list'
  | 'show-tags'
  | 'open-working-directory'
  | 'show-repository-settings'
  | 'open-external-editor'
  | 'remove-repository'
  | 'new-repository'
  | 'add-local-repository'
  | 'clone-repository'
  | 'about'
  | 'create-pull-request'
  | 'toggle-stashed-changes'
  | 'create-issue-in-repository-on-github'
  | 'cherry-pick-branch'

